title: Steem Governance Blacklist
author: Steem Governance
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The accounts who are extensively plagiarizing, spamming, milking, 
  or destroying the Steem ecosystem.

theme: minima

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  steem-governance # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
